### ISSUE TITLE
Symlinked assets are not emitted in compilation.assets

### ISSUE THREAD

**Issue by jdb8** [hmsk/symlink-webpack-plugin#3]
Because all work is being done in `after-emit`, webpack doesn't have any insight into which symlinks are produced by this plugin. This is in contrast to many other plugins which emit files: by adding the output files to `compilation.assets`, tools like `webpack-dev-server` will be able to serve the output files.

I spent some time attempting to get this working: unfortunately, since we have to account for assets being emitted as well as assets already on disk, it seems tricky to make this work for something like webpack-dev-server (which doesn't write to disk). It's possible I missed something we could use, or a simpler approach.

Any ideas on how this could work? At a minimum, having the plugin emit files for things already on disk might be a decent start. For output bundles etc. which won't be on disk at the time of `emit`, we might need a second pass using `need-additional-pass`, or set up the asset in `compilation.assets` in the `emit` stage, and then make the actual symlink later in `after-emit`. Finally, for webpack-dev-server, I'm still unsure how to handle all the above cases.

**Comment by hmsk** [comment]
Unfortunately, this plugin targeted making symlinks for bundled files under the bundled directory originally, for deployment to front-end-only hosting like surge.sh (So, naming was worse perhaps?). So I decided that don't make symlinks until all emitted files are prepared. (We can control the order of the plugin runs in `emit` phase now?)

But would like to hear more specific use-case for using symlink in dev, or the reason to require the emitted symlink 🤔  do you have any nice sample repo?
