### ISSUE TITLE
Add an optional “force” parameter

### ISSUE THREAD

**Issue by khalwat** [hmsk/symlink-webpack-plugin#5]
Thanks for your plugin, it does exactly what I need... except I need an optional `force` parameter to pass in, to create the symlink even if the target file doesn't (yet) exist. I created a PR for the changes:

https://github.com/hmsk/symlink-webpack-plugin/pull/4

**Comment by hmsk** [comment]
Fixed in c92aeafceea100e8a777e98cbcbea4fd1a566eb7
will release as v0.1.0 soon.

**Comment by hmsk** [comment]
Released. Thanks for your feedback ✨ 
https://www.npmjs.com/package/symlink-webpack-plugin
